# Generated by Django 5.0.6 on 2024-06-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
